train:
  batch_size : 4
  num_workers : 8
  learning_rate : 0.001
  decay_step : 15
  decay_gamma : 0.1
  num_epochs : 40
  save_seq : 2
  loss_lambda : 2.0
  input_size : [384, 384]
test:
  id_oneshot : [125]