train:
  batch_size : 4
  num_workers : 8
  learning_rate : 0.0005
  decay_step : 30
  decay_gamma : 0.1
  num_epochs : 90
  save_seq : 1
  loss_lambda : 5.0
  input_size : [768, 384]
test:
  id_oneshot : [118]